# Generated by Django 5.1.1 on 2025-04-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='8UUQkHYuiFkUmo5ak21GLnQ2SM1Uglwv', editable=False, max_length=32, unique=True),
        ),
    ]
