# Generated by Django 5.1.1 on 2025-07-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0007_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='h0p6Sw4rb6MEkCnRHmRufI4ByQJKM5xS', editable=False, max_length=32, unique=True),
        ),
    ]
