# Generated by Django 5.2.4 on 2025-07-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0008_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='UacVn9KgjadQq8UGUQx2VDPRgIDIv2Ih', editable=False, max_length=32, unique=True),
        ),
    ]
